.PHONY: all clean

all:
	gcc -Wall mmap.c   -o mmap
	gcc -Wall pipe.c   -o pipe
	gcc -Wall socket.c -o socket
	gcc -Wall server.c -o server
	gcc -Wall client.c -o client

clean:
	rm -f *~ mmap pipe socket server client

