.PHONY: all clean

all: 
	gcc -Wall forkseq.c   -o forkseq
	gcc -Wall forkfor.c   -o forkfor
	gcc -Wall forkaddr.c  -o forkaddr
	gcc -Wall forkexecl.c -o forkexecl
	gcc -Wall shexecl.c   -o shexecl
	gcc -Wall shexecvp.c  -o shexecvp

clean:
	rm -f *~ forkseq forkfor forkaddr forkexecl shexecl shexecvp

